#' @title aggregate NDS ping data to shift or trips new datasets.
#'
#' @description This function produce new datasets with starting and ending variables, which may include date and time, latitude, longitude.
#' @param data The data to be passed on.
#' @param trip_id The ID column generated by the `segment()` function.
#' @param threhold The threshold you want to separate the ping (in minutes). It is recommended to use 30 minutes to separate into trips, and 8*60 minutes to separate into shifts.
#' @param time_diff The time difference between the nearest two pings.
#' @keywords aggregate
#' @export
#' @examples `agg_trip(data = dat, trip_id = id)`

agg_trip = function(data, trip_id){

}
